# Generated by Django 3.1.7 on 2021-07-12 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Specs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensions', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('screen', models.CharField(max_length=200)),
                ('cpu', models.CharField(max_length=100)),
                ('gpu', models.CharField(max_length=100)),
                ('mainCam', models.CharField(max_length=50)),
                ('selfieCam', models.CharField(max_length=50)),
                ('video', models.CharField(max_length=100)),
                ('battery', models.CharField(max_length=10)),
                ('fastChar', models.BooleanField()),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mobApp.brand')),
            ],
        ),
    ]
