# Generated by Django 3.1.7 on 2021-07-12 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mobApp', '0002_auto_20210712_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specs',
            old_name='model',
            new_name='brand',
        ),
        migrations.AddField(
            model_name='specs',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
