# Generated by Django 3.1.7 on 2021-07-12 14:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mobApp', '0005_auto_20210712_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='modelName',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specs',
            name='chooseModel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mobApp.brand'),
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
