# Generated by Django 3.1.7 on 2021-07-12 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mobApp', '0006_auto_20210712_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specs',
            old_name='chooseModel',
            new_name='brand',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='modelName',
        ),
        migrations.AddField(
            model_name='specs',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
