# Generated by Django 3.1.7 on 2021-07-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobApp', '0007_auto_20210712_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specs',
            old_name='name',
            new_name='model',
        ),
    ]
