# Generated by Django 3.1.7 on 2021-07-12 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mobApp', '0008_auto_20210712_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specs',
            name='model',
        ),
        migrations.AddField(
            model_name='brand',
            name='model',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
