# Generated by Django 3.1.7 on 2021-07-12 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobApp', '0009_auto_20210712_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='model',
        ),
        migrations.RemoveField(
            model_name='specs',
            name='brand',
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(max_length=100)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobApp.brand')),
            ],
        ),
        migrations.AddField(
            model_name='specs',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mobApp.model'),
        ),
    ]
