# Generated by Django 3.1.7 on 2021-07-15 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobApp', '0010_auto_20210712_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='model',
            new_name='brand',
        ),
    ]
