# Generated by Django 3.1.7 on 2021-07-16 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobApp', '0011_auto_20210716_0136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specs',
            old_name='fastChar',
            new_name='fastCharging',
        ),
    ]
