# Generated by Django 3.1.7 on 2021-07-24 22:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mobApp', '0012_auto_20210716_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specs',
            name='model',
        ),
        migrations.AddField(
            model_name='brand',
            name='model',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specs',
            name='model_specs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mobApp.brand'),
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
