# Generated by Django 3.1.7 on 2021-07-25 00:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mobApp', '0013_auto_20210725_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand',
            new_name='brandName',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='model',
        ),
        migrations.RemoveField(
            model_name='specs',
            name='model_specs',
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(max_length=100)),
                ('createdOn', models.DateField(default=django.utils.timezone.now)),
                ('warranty', models.BooleanField()),
                ('damaged', models.BooleanField()),
                ('repaired', models.BooleanField()),
                ('firstOwner', models.BooleanField()),
                ('price', models.IntegerField(max_length=10)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mobApp.brand')),
            ],
        ),
        migrations.AddField(
            model_name='specs',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mobApp.model'),
        ),
    ]
